version: '2'

services:
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - 50000:50000
    networks:
      - jenkins
    volumes:
      - jenkins-storage:/var/jenkins_home
    environment:
      VIRTUAL_HOST: jenkins.dev
      JAVA_OPTS: -Dhudson.footerURL=http://jenkins.dev

networks:
  jenkins:

volumes:
  jenkins-storage:
      driver: local
