version: '2'

services:
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    ports:
      - 50000:50000
      - 80:8080
    networks:
      - jenkins
    volumes:
      - jenkins-storage:/var/jenkins_home
    environment:
      VIRTUAL_HOST: jenkins.dev

networks:
  jenkins:

volumes:
  jenkins-storage:
      driver: local
