version: '2'

services:
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    ports:
      - 50000:50000
      - 80:8080
    volumes:
      - jenkins-storage:/var/jenkins_home

networks:
  jenkins:

volumes:
  jenkins-storage:
      driver: local
